apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: catalog-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"] # Graceful shutdown - make Kubernetes wait for 5 seconds before sending the SIGTERM signal to the Pod
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: BPL_DEBUG_ENABLED
              value: "true"
            - name: BPL_DEBUG_PORT
              value: "8001"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://polar-postgres:5432/polardb_catalog
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
